version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
            - post_db
            - comment_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  ui:
    #build: ./ui
    image: ${USERNAME}/ui:logging
    ports:
      - ${PUB_PORT}:${PUB_PORT}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    #build: ./post-py
    image: ${USERNAME}/post:logging
    networks:
      front_net:
        aliases:
            - post
      back_net:
        aliases:
            - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    #build: ./comment
    image: ${USERNAME}/comment:logging
    networks:
      front_net:
        aliases:
            - comment
      back_net:
        aliases:
            - comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}


volumes:
  post_db:

networks:
  front_net:
  back_net:
