version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
            - post_db
            - comment_db
  ui:
    #build: ./ui
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - ${PUB_PORT}:${PUB_PORT}/tcp
    networks:
      - front_net
  post:
    #build: ./post-py
    image: ${USERNAME}/post:${VERSION}
    networks:
      front_net:
        aliases:
            - post
      back_net:
        aliases:
            - post
  comment:
    #build: ./comment
    image: ${USERNAME}/comment:${VERSION}
    networks:
      front_net:
        aliases:
            - comment
      back_net:
        aliases:
            - comment

volumes:
  post_db:

networks:
  front_net:
  back_net:
