---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: ui-ingress
  backend:
    serviceName: ui
    servicePort: 9292

---

apiVersion: v1
kind: Secret
metadata:
  name: ui-ingress
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: |
        MIICrjCCAZYCCQCLL5oa55zZ0zANBgkqhkiG9w0BAQsFADAZMRcwFQYDVQQDDA4xNzguMTU0LjIyMy4xNTAeFw0yMTA4MDMwNTEwMThaFw0yMjA4MDMwNTEwMThaMBkxFzAVBgNVBAMMDjE3OC4xNTQuMjIzLjE1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw2t74T+KFvH5OLo8aUbspstJgFxLZPfDxxnrrHwfft4jC5pQLkLHxN73X7PTkpeGytqzf0k2+9doQp17vxIU+x9Pl0v8wIynfLxbecMJOzYnOcuxx/VtimKGAG8kTMC31fQW49UHNm81WCcij/MmtUQznwSjbl71gLnNCjPKQq0gNUoG2i41phnRUlle+Dnn3Y6VHP7AycbLHCguNs4A8hf1IgHdYl8Jry3hUK9V5y1J7AK8BKghO1t91i6VTqvon6SgK317gw9aZu1YlRYG2BieEXxyW078qBcTl/169VtBi/p51k5/oGNP0Q4Y1mIKLZmpz29bhTUncXJWBnsnOQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBQlQ2LcgLf5XUaY9WBBN/cQA+qkzL1QFIzfs7Xn0pCe0T89ckrc+rlVOs+zDCT/XZhJDqT0z1CPeEtao2cwbH46hEsO+7+MMIwl+vS4rqfOzDdGyXqyR61u+ldpvq4Rnr+FdyTvCyF18Et7SGOtZK8haFlMxnYq1NqwudWN2NBUKPzoqKzmnrZrA1PI6SRUDt+2G/El/kwx6MVmZTtxdi93wuLlXE0ca+ASXNd/x6iTJTSZG9PfVsa2Nt9j0ujKQnArOnA0VkUDLYeatH7mXDNppjpb4loYWU8EmU22/AKI3UT8s5RBNoUeYkQWvYgHieG8hY67w5odl1GqJkplm7T
  tls.key: |
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDa3vhP4oW8fk4ujxpRuymy0mAXEtk98PHGeusfB9+3iMLmlAuQsfE3vdfs9OSl4bK2rN/STb712hCnXu/EhT7H0+XS/zAjKd8vFt5wwk7Nic5y7HH9W2KYoYAbyRMwLfV9Bbj1Qc2bzVYJyKP8ya1RDOfBKNuXvWAuc0KM8pCrSA1SgbaLjWmGdFSWV74OefdjpUc/sDJxsscKC42zgDyF/UiAd1iXwmvLeFQr1XnLUnsArwEqCE7W33WLpVOq+ifpKArfXuDD1pm7ViVFgbYGJ4RfHJbTvyoFxOX/Xr1W0GL+nnWTn+gY0/RDhjWYgotmanPb1uFNSdxclYGeyc5AgMBAAECggEATRVJsSj6FGDwOJMlnzVNxeEsJgjB6Jrey9uKnef8GHQRCNOeyxCmch6tHz/0tb81eTDZWt0LZj2qr5QlKtI8Gm5YW8qqcV1J96bowlfPfV64DFEv2DsUMWD5kJRGkkv2d9unZ8kw5iTputL9DCESZK/5WMFgofmtB1DC80JIhxHH9EoEC2PRLoSBzNYgb2kIfEorGyfRtEMyn0BuGXJklobaoSEaim6vFvcYgYJSqZNxu3Ju3t7eWcoKQnHtyMAVKO8APQTApqgheQWXU/jch557qDJ3BemMKaQYJGwZeA27AalQVcALMI7AdYu2twpSo597p0SP9ZFJykMOD6YlPQKBgQD2smufpDPxQXBVwwPDCGcnTnvL18xgM5j4FxfkJET6wgr6TfYyeAhb18h6YFJfwxgZ6UKyChwa7RNbzw46fQ3d8ltuw6TOwQfXSGgXAMKt2xwaNosvBZq8CCiJjwepthCdUyTTO9GAJcpHcJvFd77BgnlBAaLrSiFBTGACHmtbDwKBgQDKygqOkiUzU8LIC+nnBnTnRCGyMX2hf9bJ7zKPUJJzjmGjYDvWsNmZpyCkPeeSHNpDH9poQuFgJfkbdRil5Vrrs1CwEtH0O6izUzaYC8XFTSuKjYKqSqMM49z5PVCCXnvWqdz4FX0O153JNAKykZkJm3gJlwYC+wsISNox5Jf5NwKBgDoertxdgx9Dm4OY/jnksOjBxMixfqTrgw5v4mENanLpZEy0MVySiuWYYNLz/nQxMmxoWB4544U0dWsbzO5ap/myL3hY/2r2bzJ5DIze0P7EsEo8r23UlC/YfDRsThHdouxtui9J2IGoZY+PKCPNolNUudxm1ks4m70WkUfugrxhAoGAXQXnZ9U0iWH/9OI6Lsbwc3H2fxZiyeWpssIuED3moGmM8nPfnzFK8EgRGiZnhsgDe00uVCtx1Tg2GFlTsC4Q0hRUjCBl/UIste4TGhY0Z7hpo8ocSV+pge043YA54UPUTPloqsi4sElKURSxtBZD/Hs7yjJkCJP+UJOSu9ZfvGsCgYEAjfqtf3WOITakGSkGwGZ0zB8KTbxFPfFK/mlpUYXcGDjA0LV9lXNZQ25MvI/Fj+JL0sWXSPdjcRZ9t/XvLQNsPthrEG/tapO6pP3DkhhiWFPulEHrnYPcCdnl+V5nwx+FaJiHZO4WFr6xMXZxW0cwwd6lSLHrLlxDxNRKoCH3Kew=
